export const UK_CITIES = [
  "London",
  "Birmingham",
  "Manchester",
  "Glasgow",
  "Newcastle upon Tyne",
  "Sheffield",
  "Liverpool",
  "Leeds",
  "Bristol",
  "Belfast",
  "Edinburgh",
  "Leicester",
  "Coventry",
  "Nottingham",
  "Brighton",
  "Southampton",
  "Cardiff",
  "Plymouth",
  "Wolverhampton",
  "Stoke-on-Trent",
  "Derby",
  "Salford",
  "Portsmouth",
  "Westminster",
  "Aberdeen",
  "Oxford",
  "Cambridge",
  "York",
  "Swansea",
  "Dundee",
  "Bath",
  "Canterbury",
  "Chester",
  "Exeter",
  "Gloucester",
  "Lincoln",
  "Norwich",
  "Salisbury",
  "Winchester",
  "Worcester",
  "Carlisle",
  "St Albans",
  "Inverness",
  "Stirling",
  "Derry",
  "Lisburn",
  "Newry"
].sort();

export const UK_CITY_OPTIONS = UK_CITIES.map(city => ({
  value: city,
  label: city
}));
